"""init business tables

Revision ID: aaedea054271
Revises: 
Create Date: 2026-05-20 13:36:43.582994
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aaedea054271'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('voice_description', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('best_for', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('sample_audio_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('processed_stripe_events',
    sa.Column('stripe_event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stripe_event_id')
    )
    op.create_table('samples',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('mood', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('artist_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('order_number', sa.Text(), nullable=False),
    sa.Column('recipient_name', sa.Text(), nullable=False),
    sa.Column('recipient_nickname', sa.Text(), nullable=True),
    sa.Column('mention_name_preference', sa.Text(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('occasion', sa.Text(), nullable=False),
    sa.Column('occasion_date', sa.Date(), nullable=True),
    sa.Column('is_surprise', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('mood', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('tempo', sa.Text(), nullable=True),
    sa.Column('song_length', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('favorite_memories', sa.Text(), nullable=True),
    sa.Column('how_they_met', sa.Text(), nullable=True),
    sa.Column('what_makes_them_special', sa.Text(), nullable=True),
    sa.Column('inside_jokes', sa.Text(), nullable=True),
    sa.Column('important_dates_places', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('desired_feelings', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('things_to_avoid', sa.Text(), nullable=True),
    sa.Column('package_type', sa.Text(), nullable=False),
    sa.Column('delivery_speed', sa.Text(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending_payment', nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), server_default='usd', nullable=False),
    sa.Column('stripe_checkout_session_id', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Text(), server_default='unpaid', nullable=False),
    sa.Column('share_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email_type', sa.Text(), nullable=False),
    sa.Column('recipient_email', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lyrics',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('lyrics_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('generated_by', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyrics_order_id'), 'lyrics', ['order_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('revisions',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('revision_type', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='requested', nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_order_id'), 'revisions', ['order_id'], unique=False)
    op.create_table('song_briefs',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title_ideas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emotional_arc', sa.Text(), nullable=True),
    sa.Column('must_include', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('must_avoid', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_ai_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_briefs_order_id'), 'song_briefs', ['order_id'], unique=False)
    op.create_table('song_files',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_files_order_id'), 'song_files', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_files_order_id'), table_name='song_files')
    op.drop_table('song_files')
    op.drop_index(op.f('ix_song_briefs_order_id'), table_name='song_briefs')
    op.drop_table('song_briefs')
    op.drop_index(op.f('ix_revisions_order_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_lyrics_order_id'), table_name='lyrics')
    op.drop_table('lyrics')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('samples')
    op.drop_table('processed_stripe_events')
    op.drop_table('artists')
    # ### end Alembic commands ###
