"""File storage (PDD §26).

Primary: Cloudflare R2 (S3-compatible), private with presigned URLs.
Fallbacks so the app runs without R2:
  - external provider URLs (e.g. Replicate/Suno) are stored as-is.
  - generated bytes are written to a local MEDIA_DIR and served at /media.

`storage_key` conventions:
  - "http..."        -> external URL, returned as-is
  - "local:<name>"   -> file in MEDIA_DIR, served at /media/<name>
  - anything else    -> R2 object key, presigned on read
"""

import pathlib

import boto3
from botocore.client import Config

from app.core.config import settings

MEDIA_DIR = pathlib.Path(__file__).resolve().parents[2] / "media"


def r2_configured() -> bool:
    return bool(settings.r2_account_id and settings.r2_access_key_id)


def _client():
    return boto3.client(
        "s3",
        endpoint_url=f"https://{settings.r2_account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=settings.r2_access_key_id,
        aws_secret_access_key=settings.r2_secret_access_key,
        config=Config(signature_version="s3v4"),
        region_name="auto",
    )


def presigned_get_url(key: str, expires_in: int = 3600) -> str:
    return _client().generate_presigned_url(
        "get_object",
        Params={"Bucket": settings.r2_bucket, "Key": key},
        ExpiresIn=expires_in,
    )


def presigned_put_url(key: str, content_type: str, expires_in: int = 3600) -> str:
    return _client().generate_presigned_url(
        "put_object",
        Params={"Bucket": settings.r2_bucket, "Key": key, "ContentType": content_type},
        ExpiresIn=expires_in,
    )


def store_bytes(key: str, data: bytes, content_type: str) -> str:
    """Persist bytes. Returns the storage_key to record on the SongFile."""
    if r2_configured():
        _client().put_object(
            Bucket=settings.r2_bucket, Key=key, Body=data, ContentType=content_type
        )
        return key
    # local fallback
    MEDIA_DIR.mkdir(parents=True, exist_ok=True)
    name = key.replace("/", "_")
    (MEDIA_DIR / name).write_bytes(data)
    return f"local:{name}"


def public_url(storage_key: str) -> str:
    """Resolve a SongFile.storage_key to a fetchable URL."""
    if storage_key.startswith("http://") or storage_key.startswith("https://"):
        return storage_key
    if storage_key.startswith("local:"):
        name = storage_key.split(":", 1)[1]
        return f"{settings.api_base_url}/media/{name}"
    return presigned_get_url(storage_key)
